config/routes.rb
Rails.application.routes.draw do

  #Casein routes
  namespace :casein do
    resources :customers
  end

  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/casein/customers_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CustomersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Customers'
  		@customers = Customer.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View customer'
      @customer = Customer.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new customer'
    	@customer = Customer.new
    end

    def create
      @customer = Customer.new customer_params
    
      if @customer.save
        flash[:notice] = 'Customer created'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new customer'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update customer'
      
      @customer = Customer.find params[:id]
    
      if @customer.update_attributes customer_params
        flash[:notice] = 'Customer has been updated'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to update this customer'
        render :action => :show
      end
    end
 
    def destroy
      @customer = Customer.find params[:id]

      @customer.destroy
      flash[:notice] = 'Customer has been deleted'
      redirect_to casein_customers_path
    end
  
    private
      
      def customer_params
        params.require(:customer).permit(:name, :age, :date_of_birth, :has_paid)
      end

  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :casein, :action => :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/casein/customers/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :age %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_date_select f, f.object, :date_of_birth %>
	</div>
	<div class="col-lg-6">
		<%= casein_check_box f, f.object, :has_paid %>
	</div>
</div>

app/views/casein/customers/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Age", :age %></th>
			<th><%= casein_sort_link "Date of birth", :date_of_birth %></th>
			<th><%= casein_sort_link "Has paid", :has_paid %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% customers.each do |customer| %>
		<tr>
			<td><%= casein_table_cell_link customer.name, casein_customer_path(customer) %></td>
			<td><%= casein_table_cell_link customer.age, casein_customer_path(customer) %></td>
			<td><%= casein_table_cell_link customer.date_of_birth, casein_customer_path(customer) %></td>
			<td><%= casein_table_cell_link customer.has_paid, casein_customer_path(customer) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_customer_path(customer), :method => :delete, :data => { :confirm => "Are you sure you want to delete this customer?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/customers/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Customers<%= casein_pagination_details @customers %></h2>

<%= render :partial => 'casein/customers/table', :locals => { :customers => @customers } %>

<div class="text-center">
	<%= will_paginate @customers %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new customer".html_safe, new_casein_customer_path %></li>

<% end %>

app/views/casein/customers/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new customer</h2>

<%= form_for @customer, :url => casein_customers_path do |f| %>
	
	<%= render :partial => 'casein/customers/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_customers_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new customer", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_customers_path %></li>
<% end %>

app/views/casein/customers/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View customer</h2>

<%= form_for @customer, :url => casein_customer_path(@customer) do |f| %>

	<%= render :partial => 'casein/customers/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_customers_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_customers_path %></li>
<% end %>

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-customers"><%= link_to "Customers", casein_customers_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/customers/index.html.erb
<h1>Customers</h1>

<% @customers.each do |customer| %>
  <ul>
    <%= content_tag('li', customer.name) %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Casein</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>